message("\n[Properties | GLOBAL]")
get_cmake_property(cacheVariables CACHE_VARIABLES)
message("  Cache variables: ${cacheVariables}")

message("\n[Properties | DIRECTORY]")
get_directory_property(sourceDir SOURCE_DIR)
message("  Current source directory: ${sourceDir}")
set_directory_properties(PROPERTIES LABELS "Chapter10")
message("  Set labels: Chapter10")
get_directory_property(labels LABELS)
message("  Labels: ${labels}")
